spring.application.name=trading_alert

server.port=8081

spring.data.mongodb.uri=mongodb+srv://janhavi08511:jkp%2347@cluster0.a1hn6bf.mongodb.net/Trading

firebase.service-account.path=${FIREBASE_SERVICE_ACCOUNT_PATH:}
app.notification.base-url=${APP_BASE_URL:http://localhost:8081}

